#4 ファイルを追加しました
Hazel2/TestRepos pull request #5
Opened 2017-12-14 04:58 UTC by Hazel2

演習3.5

2017-12-14 08:30 UTC, Hazel2 commented on junio_hamano.md
> +I am Junio Hamano!
ｓｓｓ

2017-12-15 01:23 UTC, akawato requested changes
XXを追加してください。

2017-12-15 01:23 UTC, akawato commented on junio_hamano.md
> +I am Junio Hamano!
これはどういう意味ですか？

2017-12-15 02:55 UTC, akawato approved these changes
OKです。

2017-12-15 04:11 UTC, merged